ktor {
  database {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://localhost:5432/testdb"  # для внешней БД
    user = "testuser"
    password = "testpass"
    maxPoolSize = 5
  }
}

# "container" или "external"
test {
  database {
    mode = "container"
  }
}
